In [1]:
import numpy as np
a= np.array([[np.arange(1,3)],[np.arange(4,6)]])
print('array1_2d:',a)# 2d array arange
b= np.array([[np.linspace(0,10,3)],[np.linspace(11,21,3)]])
print('array2_2d:',b) #2d array linspace
c=np.array([[[np.arange(1,4)],[np.arange(4,7)]],[[np.arange(7,10)],[np.arange(10,1)]]])
print('array1_3d:',c) #3d array arange
d=np.array([np.linspace(0,60,12)])
print('array2_3d:',d.reshape(2,3,2)) #3d array linspace

array1_2d: [[[1 2]]

 [[4 5]]]
array2_2d: [[[ 0.  5. 10.]]

 [[11. 16. 21.]]]
array1_3d: [[[array([1, 2, 3])]
  [array([4, 5, 6])]]

 [[array([7, 8, 9])]
  [array([], dtype=int32)]]]
array2_3d: [[[ 0.          5.45454545]
  [10.90909091 16.36363636]
  [21.81818182 27.27272727]]

 [[32.72727273 38.18181818]
  [43.63636364 49.09090909]
  [54.54545455 60.        ]]]


<ipython-input-1-cab2867725a8>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  c=np.array([[[np.arange(1,4)],[np.arange(4,7)]],[[np.arange(7,10)],[np.arange(10,1)]]])


In [2]:
#2. Write a NumPy program to reverse an array (first element becomes last).
a=np.array(np.arange(12,38))
print('array:',a)
print('reverse array:',a[::-1])

array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [3]:
# 3. Write a NumPy program to find the number of elements of an array, length of array and bytes of array
a=np.array(np.arange(1,6))
print('size of array:',a.size)
print('length of one array element in bytes:',a.itemsize)
print('total bytes consumed by the elements of the array:',a.nbytes)


size of array: 5
length of one array element in bytes: 4
total bytes consumed by the elements of the array: 20


In [4]:
#4. Write a NumPy program to construct an array by repeating
a=np.array([0,1,2])
print('original:',a)
print('repit 2 time:',np.tile(a,2))
print('repit 3 time:',np.tile(a,3))

original: [0 1 2]
repit 2 time: [0 1 2 0 1 2]
repit 3 time: [0 1 2 0 1 2 0 1 2]


In [5]:

#5. Write a NumPy program to repeat elements of an array.

a=np.array([0])
print('a=',np.repeat(a,4))
b=np.array([1,2,3,4])
print('b=',np.repeat(b,3))

a= [0 0 0 0]
b= [1 1 1 2 2 2 3 3 3 4 4 4]


In [6]:
#6. Write a NumPy program to create a new array of 3*5, filled with 2.

a=np.full((3, 5), 2)
print(a)


[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [8]:
#8. Write a NumPy program to append values to the end of an array.

a=np.array([0,1,2])
print('a before:',a)
a=np.append(a,[3,4,5,6,7,8])
print('after append a:',a)


a before: [0 1 2]
after append a: [0 1 2 3 4 5 6 7 8]


In [9]:
# one array element present in second array check.

a=np.array([0,1,2,3,4])
b=np.array([0,2,4])
print('a:',a)
print('b:',b)
print(np.in1d(a,b))

a: [0 1 2 3 4]
b: [0 2 4]
[ True False  True False  True]


In [10]:
#12. Write a NumPy program compare two given arrays.

a=np.array([1,4])
b=np.array([3,4])
print('a>b:',a>b)
print('a>=b',a>= b)
print('a<b:',a< b)
print('a<=b',a<= b)

a>b: [False False]
a>=b [False  True]
a<b: [ True False]
a<=b [ True  True]


In [11]:
#14. Write a NumPy program to create 1D array and convert 1D array to 2D array and 3d
a=np.array(np.arange(1,28))
print('1d :',a)
b=a.reshape(3,9)
print('2d :',b)
print('3d :',b.reshape(3,3,3))

1d : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
2d : [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
3d : [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
#15. Write a NumPy program to implement vstack and hstack method on 2D array
a=np.array([1,2,3])
print('a:',a)
print(np.hstack((a,[4,5,6])))
print(np.vstack((a,[4,5,6])))

a: [1 2 3]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np


In [10]:
a = np.abs(30)

In [11]:
a

30